### ISSUE TITLE
Tanker om `/alle` endepunkt

### ISSUE THREAD

**Issue by Andersos** [netliferesearch/stammespraak#5]
Vil det ha noen verdi å legge til et `/alle` endepunkt som lister du alle ordene uten definisjon?

**Comment by kmelve** [comment]
Jeg lurte på om vi heller skulle ha forsiden sånn? Men dette kan jo like gjerne være /alle ja :)
<img width="854" alt="2017-04-24 at 09 53" src="https://cloud.githubusercontent.com/assets/1131579/25327316/f833ecc0-28d3-11e7-890e-c9d0fe19b1fb.png">

**Comment by Andersos** [comment]
Hehe, jeg hadde egentlig tenkte å sende en pull request med endringsforslag men tenkte jeg skulle spørre først. Nå må jeg finne på en annen ting jeg kan bidra med =) Uansett kult 👍

**Comment by kmelve** [comment]
ah, jeg hadde jo dette klart lokalt da du spurte også. great minds think alike :)

**Comment by Andersos** [comment]
Konge, om du skulle komme på noe annet gi beskjed =)
